# Config for Troll v1.2 by Gaming12846
message:
  nopermission: 'You have no permission to do that'
  noconsole: 'The console cannot use this command'
  usagetrollmenu: 'Please use </troll Player>'
  targetnotonline: 'The Player [Player] is currently not online'

banmessage:
  banmessageplayer: 'You have been banned from this Server'
  bankmessagebroadcastonoff: true
  banmessagebroadcast: 'The Player [Player] have been permanently banned from the server'

spammessages:
  - 'testmessage1'
  - 'testmessage2'
  - 'testmessage3'