# Config for TrollPlus v1.3.3 by Gaming12846 <https://www.spigotmc.org/resources/troll-plus.81193> <https://github.com/Gaming12846/TrollPlus> <https://discord.com/invite/XvK2UMfGEJ>
switches:
  banMessageBroadcastSwitch: true
messages:
  noPermission: 'You have no permission to do that'
  noConsole: 'The console cannot use this command'
  usageTrollmenu: 'Please use </troll player>'
  usageBlacklist: 'Please use </trollblacklist [add/remove] player>'
  targetNotOnline: 'The Player [Player] is currently not online'
  immune: 'The Player [Player] is immune'
  notAllowedControl: 'You cannot control yourself'
  addedBlacklist: 'The Player [Player] has been added to the blacklist'
  removedBlacklist: 'The Player [Player] has been removed from the blacklist'
  allreadyInBlacklist: 'The Player [Player] is already in the blacklist'
  notInBlacklist: 'The Player [Player] is not on the blacklist'
  banMessageBroadcast: 'The Player [Player] have been permanently banned from the server'
  banMessagePlayer: 'You have been banned from this Server'
  semiBanMessage: '<[Player]>'
spamessages:
  - 'spammessage1'
  - 'spammessage2'
  - 'spammessage3'
  - 'spammessage4'
  - 'spammessage5'
