# Config for Troll Plus v1.3.2 by Gaming12846
messages:
  noPermission: 'You have no permission to do that'
  noConsole: 'The console cannot use this command'
  usageTrollmenu: 'Please use </troll player>'
  usageBlacklist: 'Please use </trollblacklist [add/remove] player>'
  targetNotOnline: 'The Player [Player] is currently not online'
  immune: 'The Player [Player] is immune'
  addedBlacklist: 'The Player [Player] has been added to the blacklist'
  removedBlacklist: 'The Player [Player] has been removed from the blacklist'
  allreadyInBlacklist: 'The Player [Player] is already in the blacklist'
  notInBlacklist: 'The Player [Player] is not on the blacklist'
  banMessageBroadcast: 'The Player [Player] have been permanently banned from the server'
  banMessagePlayer: 'You have been banned from this Server'
  semiBanMessage: '<[Player]>'
switches:
  banMessageBroadcastSwitch: true
spamessages:
  - 'spammessage1'
  - 'spammessage2'
  - 'spammessage3'
  - 'spammessage4'
  - 'spammessage5'