main: de.gaming12846.trollplus.main.Main
name: TrollPlus
version: 1.3.3
api-version: 1.17

description: A simple plugin for trolling players in Minecraft
author: Gaming12846
website: https://www.spigotmc.org/resources/troll-plus.81193 https://github.com/Gaming12846/TrollPlus https://discord.com/invite/XvK2UMfGEJ

commands:
     troll:
          description: Opens the troll menu
          aliases: [t]
          usage: Simply type </troll Player>
     trollblacklist:
          description: Add or remove players from the blacklist
          aliases: [tb]
          usage: Simply type </trollblacklist [add/remove] Player>